### ISSUE TITLE
http://ft-next-front-page.herokuapp.com/__ijento/uk Failed to load resource

### ISSUE THREAD

**Issue by charypar** [Financial-Times/next-front-page#10]
`http://ft-next-front-page.herokuapp.com/__ijento/uk Failed to load resource: the server responded with a status of 404 (Not Found)` client-side error. Assume this means we're missing an integration with Injento.

**Comment by imranolas** [comment]
Seems to be an issue only in non-production environments.

**Comment by matthew-andrews** [comment]
yup this will go through https://github.com/Financial-Times/next-ijento see next-registry.ft.com
