### ISSUE TITLE
Taxonomy tag underline colour black when not hovered directly over the word

### ISSUE THREAD

**Issue by clmntnbrn** [Financial-Times/next-front-page#103]
If you hover over the taxonomy the underline is the same as the text colour, if you hover over a different part of the active area the underline is black. Ask me for a demo if that makes no sense ;)

**Comment by charypar** [comment]
What browser is it in? And is it any tax tag? Can you test again, pls?

**Comment by clmntnbrn** [comment]
Only checked chrome so far, seems to be every tag - I can give you a demo, it's tricky!

**Comment by charypar** [comment]
Underline was removed by #202.
