### ISSUE TITLE
Remove bookmark icon from lead card (for now)

### ISSUE THREAD

**Issue by clmntnbrn** [Financial-Times/next-front-page#104]

**Comment by charypar** [comment]
What's the reson behind it? (also why is it a bug?)

**Comment by clmntnbrn** [comment]
@a-rhombus and I are going to redesign this as it's confusing for users - which article are they bookmarking? So we decided to remove it until the design work is done :)

**Comment by charypar** [comment]
Do we have a story for the "card toolbar" work?

/cc @SelinaBans1

**Comment by SelinaBans1** [comment]
'card toolbar' what are you referring to exactly? is that what we're calling the redesigning? @charypar

**Comment by charypar** [comment]
@SelinaBans1 The bookmarking, following and all the other stuff next front page used to have.

**Comment by commuterjoy** [comment]
> all the other stuff next front page used to have.

:+1:
