### ISSUE TITLE
Tax link are broken for most tags

### ISSUE THREAD

**Issue by charypar** [Financial-Times/next-front-page#107]
Links contain `/sectionsId/` but for most links that segment is something else, `regionsId` for instance.

**Comment by charypar** [comment]
Also we need to think about how not to ship broken stuff like this :(

**Comment by imranolas** [comment]
This is fixed already on PR #106, however, a bower dependency changed in the meantime and broke the build.

**Comment by matthew-andrews** [comment]
@charypar the business understands that bugs sometimes happen in software and so far have made it clear that they'd rather that we move quickly than worry too much (have you heard about service leave tiers?  Bronze, silver, gold, platinum - basically levels of support & robustness - everything about next is bronze except for the opt out journey which should be higher than that) so as long as we don't break opt out and people can still get to the content it's unfortunate but not bad to ship the occasional bug… or at least the business should understand :).

I personally think you folks did brilliantly with this one - it was resolved quickly (within a couple of hours of it being reported) before it had much chance to impact many customers.

If you can think of a neat way to catch this kind of thing in an automated test would love to roll that out across the whole site though!

**Comment by matthew-andrews** [comment]
Service level*

**Comment by charypar** [comment]
@matthew-andrews that's fair enough, I heard about the service levels but it still makes me feel a bit bad :) ...and think of ways to prevent it in the future, obvs without hurting the speed
