### ISSUE TITLE
easy option to save frontpage data locally for testing/dev

### ISSUE THREAD

**Issue by leggsimon** [Financial-Times/next-front-page#1076]
So I have been finding it very useful to intercept and save the graphQL response and manipulate it but it's a bit of a pain to keep going in and making the same changes every time I want to do that.

I want to propose something like a `make local-data` command and add in something like the following [here](https://github.com/Financial-Times/next-front-page/blob/master/server/routes/front-page.js#L52).
```js
const fs = require('fs');

const data = {
	frontPage: getData(frontPageData)
};

if (process.env.USE_LOCAL_DATA) {
  fs.stat('../../frontPageData.json', function(err, stat) {
    if(err == null) {
        console.log('File exists');
    } else if(err.code == 'ENOENT') {
        // file does not exist
        fs.writeFile('frontPageData.json', JSON.stringify(data.frontPage, null, 2), (err) => {
          if (err) throw err;
          console.log('It\'s saved!');
        });
    } else {
        console.log('Some other error: ', err.code);
    }
  });
  const testData = require('../../frontPageData.json');
  data.frontpage = testData;
}
```

Thoughts? Would this be useful to others?

**Comment by ironsidevsquincy** [comment]
What's an example of why you'd want to manually change the data?

**Comment by adgad** [comment]
Could you just use Charles' map-local to achieve the same effect?

**Comment by leggsimon** [comment]
@ironsidevsquincy So the reason why I've been doing it a lot recently was to force content to be Video types in certain slots.

@adgad I hadn't thought of doing a Charles mapping actually maybe that would be easier but if you wanted the data to be somewhat up to date you'd still have intercept a recent response...

**Comment by ironsidevsquincy** [comment]
We also have a 'return mock data' option from graphql - https://github.com/Financial-Times/next-graphql-api/blob/master/server/routes/query.js#L20

**Comment by aintgoin2goa** [comment]
I've got a vague memory of implementing something like this before.  the mock data feature in graphql I didn't find useful as I couldn't manipulate what was returned.  I can't remember how it worked now, though...

**Comment by leggsimon** [comment]
This has kind of been fixed by `make fixtures`
