### ISSUE TITLE
not all topics are clickable on related articles (e.g comment & leaked)

### ISSUE THREAD

**Issue by SelinaBans1** [Financial-Times/next-front-page#108]
![screen shot 2015-07-10 at 10 20 41](https://cloud.githubusercontent.com/assets/13151730/8615712/1b169016-26ed-11e5-8719-1827e0eac577.png)

**Comment by charypar** [comment]
I believe that's a problem with data fetching. I think it can be solved by actually pulling the related articles in whole and handling them as any other story card would.

**Comment by charypar** [comment]
Resolved by #75
