### ISSUE TITLE
Split GraphQL query 

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next-front-page#1157]
Currently the front page is powered by a single, enormous GraphQL query polled every minute or so. Simon's testing shows the GraphQL service locks up quickly with only a small number of large (slow to assemble) queries but performs much better with multiple small queries.

This may be because Node is not ideal for processing heavy tasks, it's much better to pop things on and off the event loop as fast as possible.

This would also allow us to poll at different rates from the front-page app and further lighten the load on the GraphQL service. E.G. headlines -> 30 secs, videos -> 5 mins

**Comment by i-like-robots** [comment]
CC @leggsimon @aintgoin2goa

**Comment by ironsidevsquincy** [comment]
👍 👍 👍 👍 👍

**Comment by leggsimon** [comment]
Yeah I like this idea, will possibly look into doing this today/tomorrow

**Comment by aintgoin2goa** [comment]
Have already done this - Am refactoring data side of front page and did it on the side.  Is in a branch now, but will prob be opening a PR soon

**Comment by leggsimon** [comment]
Oh cool!

**Comment by leggsimon** [comment]
This can be closed now @aintgoin2goa ?

**Comment by aintgoin2goa** [comment]
Yep
