### ISSUE TITLE
"Add to myFT" button on US Election headpiece not working

### ISSUE THREAD

**Issue by aendrew** [Financial-Times/next-front-page#1183]
Clicking the button yields the following error 500:

<img width="871" alt="screen shot 2016-10-25 at 15 08 33" src="https://cloud.githubusercontent.com/assets/185041/19689374/13858242-9ac5-11e6-9aca-d65c07ecf4a7.png">

cc: @aintgoin2goa as per @callumlocke's request.

**Comment by aendrew** [comment]
Being instantiated via:
`{{> myft/follow-button name="US Election 2016" id="N2UxNTM3MzItNWNlZC00MDc5LWI3ODUtYWNmZDA2YjE0MWE2-U2VjdGlvbnM="}}`

**Comment by debugwand** [comment]
https://github.com/Financial-Times/next-front-page/pull/1211

**Comment by aendrew** [comment]
Fixed by #1211. Thanks @debugwand!
