### ISSUE TITLE
US election headpiece, various changes round 3

### ISSUE THREAD

**Issue by kavanagh** [Financial-Times/next-front-page#1189]
- [x] Markets SVG loading!!
- [x] Jumpy tabby issue
- [x] CSS loading on slow loading (net throttled). CSS doesn't seem to load at the same time as the res of the CSS. including big image loading
- [x] Off-center triangle, does a SVG triangle (plus IE8 solution) fix it?
- [x] No spinner when 0 or 1 tabs visible (including when Markets tab is the only tab and it has failed to load)
- [x] Map link design change
- [x] "FULL RESULTS MAP" link behind the `frontPageUSElectionHeadpieceInteractive` flags
- [x] Selector specificity on main story stand first
- [x] White numbers in bars
- [x] `margin: 0 auto` on markets tab graphic, currently left aligned
- [x] move usElectionHeadpiece init to below CSS loader in case of failure (and write a comment to say so)
- [ ] Test with an open live blog
- [ ] Test with new stories, different length headlines
- [ ] Follow button not working

**Comment by aendrew** [comment]
Closed by #1198.
