### ISSUE TITLE
Responsive image loading

### ISSUE THREAD

**Issue by charypar** [Financial-Times/next-front-page#131]
As a performance enhancement, we should probably decide on an image size to fetch based on the device screen size - no point fetching a 720 pixel image if it's only ever gonna get used at the width of 240.

This should get us a better full page load speed on mobile devices.

**Comment by commuterjoy** [comment]
Assume you are referring to https://github.com/Financial-Times/n-image 

/cc @tom-parker

**Comment by charypar** [comment]
@commuterjoy yep, looks like that's what we want :)

**Comment by charypar** [comment]
This is fairly high priority now as m.ft.com will likely be redirected soon.
