### ISSUE TITLE
Diagnose slow font loading

### ISSUE THREAD

**Issue by charypar** [Financial-Times/next-front-page#132]
The fonts used on the page seem to be coming in a bit slow on some request. It would be good to find out why and how we can either speed that up or at least provide a decent reading experience before they come in.

**Comment by kaelig** [comment]
With @phamann on the team it's a matter of time until these bad boys get lazy loaded *à la Guardian*.

**Comment by charypar** [comment]
Spent a bit of time thinking about this, lazy loading sounds good, but it may not be needed if we manage to slim down the font set we use and optimise the file sizes and caching strategy. Parking this for now.
