### ISSUE TITLE
Potentially funky styling on Galaxy S3

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-front-page#164]
Potentially because unfortunately I don't have a device to hand to test.  I can help get access if you also don't have one.

It comes from our colleagues in customer services.

![unnamed 1](https://cloud.githubusercontent.com/assets/825088/9112007/c9f6d03a-3c43-11e5-8447-fa4168570fad.png)

> The images do not display properly on the home page ( I am using Samsung Galaxy S3 and I am not sure if this is how it looks like on other devices). But clicking the link will direct you to the page where you can view it nicely along with the rest of the article.

**Comment by matthew-andrews** [comment]
Oh, apparently it's fixed now.

> I checked the next ft site in Samsung S3 and the images are displaying properly now.


![unnamed 2](https://cloud.githubusercontent.com/assets/825088/9112804/e9e0d396-3c48-11e5-9413-bf71ba4179dc.png)

**Comment by charypar** [comment]
Closing as we have a similar one (#93) and it's likely to have been fixed by many changes happening since. Will reopen if spotted again,
