### ISSUE TITLE
Inspectlet not tracking scrolling

### ISSUE THREAD

**Issue by a-rhombus** [Financial-Times/next-front-page#178]
Inspectlet does not appear to be working on scroll for the last week.

**Comment by imranolas** [comment]
Seems ok for me :/
<img width="409" alt="screen shot 2015-08-11 at 12 13 05" src="https://cloud.githubusercontent.com/assets/4206028/9196345/5ce92cee-4022-11e5-8959-61be9a60476c.png">

**Comment by charypar** [comment]
@a-rhombus is this still an issue on your side?

**Comment by charypar** [comment]
Seems to be an Inspectlet issue. Can't fix that from our end :(
