### ISSUE TITLE
Missing styling for saved notifications

### ISSUE THREAD

**Issue by charypar** [Financial-Times/next-front-page#19]
There is an unstyled notification appearing when you save an article on the home page.
 
/cc @imranolas

**Comment by clmntnbrn** [comment]
Could this please look like the one on the current next site

**Comment by charypar** [comment]
![notification](https://cloud.githubusercontent.com/assets/1517854/8432366/8d5f9c3e-1f37-11e5-92b1-0de926f3b96b.png)
