### ISSUE TITLE
Border in Editor's Picks & Video elongated in Firefox

### ISSUE THREAD

**Issue by clmntnbrn** [Financial-Times/next-front-page#206]
Should be dots, look like dashes

<img width="483" alt="screen shot 2015-08-17 at 12 07 22" src="https://cloud.githubusercontent.com/assets/12392657/9303744/951a61e0-44d8-11e5-9db8-54add8ceb019.png">

**Comment by shirin1412** [comment]
Outdated and can be closed (Layout supersedes this stuff)
