### ISSUE TITLE
Additional line below lead video

### ISSUE THREAD

**Issue by imranolas** [Financial-Times/next-front-page#217]
The line just below the lead video title needs removing

<img width="458" alt="screen shot 2015-08-21 at 16 36 34" src="https://cloud.githubusercontent.com/assets/4206028/9412325/f8d2ad30-4822-11e5-91ad-a21e84f04d14.png">

**Comment by dilipvaghela** [comment]
Shipped to Jira : https://jira.ft.com/browse/NFT-250
