### ISSUE TITLE
Tablet: bad zoom level on device orientation change

### ISSUE THREAD

**Issue by aRhombus** [Financial-Times/next-front-page#221]
Portrait resizes properly, but when turning to landscape the viewport doesn't adjust properly.

**Comment by clmntnbrn** [comment]
Happens on ipad and ipad mini

**Comment by kaelig** [comment]
Have you tried adding `html { -webkit-text-size-adjust: 100%; }`?

**Comment by charypar** [comment]
Only happens on iOS 6, later iOS devices behave correctly.
