### ISSUE TITLE
Incorrect tab highlighted

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/next-front-page#232]
Front page mobile bug. Click on fastft tab, click on fastft article, go back - incorrect tab is highlighted

![image](https://cloud.githubusercontent.com/assets/447559/9600690/619fd350-5094-11e5-8059-cdde3e4e4c25.png)

**Comment by charypar** [comment]
Cannot reproduce on iPhone, only in Chrome.

**Comment by wheresrhys** [comment]
Fastft tab now missing from mobile. Is this a feature or bug?

**Comment by imranolas** [comment]
It's a bug #236

**Comment by SelinaBans1** [comment]
@charypar  i think this is fixed now - happy to close it?
