### ISSUE TITLE
QA issue - sticky nav

### ISSUE THREAD

**Issue by SelinaBans1** [Financial-Times/next-front-page#238]
- header not sticky on safari, ios6

**Comment by charypar** [comment]
May be relevant: http://igstudio.blogspot.de/2012/09/positionfixed-in-ios-6.html

**Comment by charypar** [comment]
Also, can we log nav bugs on the nav repo, pls? https://github.com/Financial-Times/n-header-footer/issues

**Comment by charypar** [comment]
Replaced by Financial-Times/n-header-footer#66
