### ISSUE TITLE
Fix memory leaks and elastic search 'DDOS-ing'

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/next-front-page#241]
Several times over the last few weeks requests from front-page to elastic search and capi-page have spiked. This correlates with memory spikes in front-page (unsure of the causal relationship). On the last occasion (2 September) it looks to have caused big problems in elastic search's responses (though again, causality isn't 100% certain here), which in turn impacted on next-article and stream page (user facing errors). As next-article is responsible for delivering access metadata responses too, it triggered nagios alerts in the *aim* team

![image](https://cloud.githubusercontent.com/assets/447559/9656137/fb2ec63a-522d-11e5-9e52-22bb973f5b23.png)

**Comment by wheresrhys** [comment]
eager-fetch for elastic search requests has been disabled https://github.com/Financial-Times/next-ft-api-client/releases/tag/v3.10.2 to mitigate the problem for the time being. Once the problem is fixed here we should consider whether or not to revert the change https://github.com/Financial-Times/next-ft-api-client/pull/47 @matthew-andrews

**Comment by matthew-andrews** [comment]
When we have @phamann's circuit breakers I think we can consider switching it back on.

**Comment by charypar** [comment]
Looks like #242 fixed the problem

![](https://www.hostedgraphite.com/bbaf3ccf/569381f9-6a60-4c33-a0be-b2272aa7a4a5/graphite/render/?_salt=1416939293.909&bgcolor=FFFFFF&fgcolor=000000&target=heroku.front-page.*.system.process.mem_process_*&target=color(drawAsInfinite(heroku.front-page.*.express.start),%27black%27)&width=801&height=300&lineMode=connected&from=-10d)

**Comment by charypar** [comment]
Closing, we can reopen if we see the problem again.
