### ISSUE TITLE
install: bower packages

### ISSUE THREAD

**Issue by bsr203** [Financial-Times/next-front-page#260]
The install step in README seems incomplete. How to install all the bower components? just doing `bower install` doesn't work as the packages use shorthand. I made a `bowerrc` file with the below content, but still doesn't work. thanks.

```

{
	  "shorthand-resolver": "https://github.com/Financial-Times/{{package}}"
}

```

**Comment by matthew-andrews** [comment]
@bsr203 hi, the instructions for all our apps are here:- http://financial-times.github.io/next/docs/developer-guide/#make

Also, who are you? :smile:

**Comment by bsr203** [comment]
hi.. thanks for the link. I just saw the talk by Viktor https://www.youtube.com/watch?v=S0s935RKKB4 and was trying out graphql and an advanced example. :-)

**Comment by matthew-andrews** [comment]
Aha !  I should warn you in advance that this repository is not easy to run without certain API keys that allow privileged access to FT content.

You're welcome than welcome to study the code and _try_ to get it running, but it probably won't be possible.

… We are hiring if you've got right to work in the EU and are interested in this sort of technology :innocent: …

**Comment by bsr203** [comment]
:-) thanks.. It might better just official graphql/relay examples and just read your code. thanks for opensourcing them.

I live in USA and indeed the unsettling changes in front end tools are frameworks are my new found interest :-) I am self employed and an aspiring entrepreneur. react/flux/relay are my focus now. Love to have a remote contract opportunity.
