### ISSUE TITLE
Got an error when running `webpack`

### ISSUE THREAD

**Issue by haohcraft** [Financial-Times/next-front-page#261]
Got the error below when running `make build`, any idea about this?

ERROR in /Users/hhuang/Documents/play/next-front-page/node_modules/css-loader/node_modules/cssnano/node_modules/autoprefixer-core/node_modules/caniuse-db/data.json: Unexpected end of input
 @ multi main

**Comment by charypar** [comment]
Sounds like an interrupted `npm install`, maybe? 

Please note that this app won't work stand-alone, it's part of the Next FT project and requires configuration variables from private repositories (api secrets, etc). You're welcome to study the code, but you won't be able to run it.

**Comment by haohcraft** [comment]
I see, thanks
