### ISSUE TITLE
"Go to" links missing

### ISSUE THREAD

**Issue by clmntnbrn** [Financial-Times/next-front-page#28]
Please add links & arrows

![screen shot 2015-06-30 at 10 43 21](https://cloud.githubusercontent.com/assets/12392657/8428216/008f74f4-1f15-11e5-820a-c6b3f0ef830e.png)
![screen shot 2015-06-30 at 10 43 39](https://cloud.githubusercontent.com/assets/12392657/8428215/008f6ea0-1f15-11e5-9698-3d0b3ae7dd2c.png)
![screen shot 2015-06-30 at 10 43 46](https://cloud.githubusercontent.com/assets/12392657/8428217/0094069a-1f15-11e5-87f8-3870bbef8a63.png)

**Comment by imranolas** [comment]
All fine except for Editor's picks, which is a selection of articles from a number of sources and doesn't have it's own page to link to.

**Comment by clmntnbrn** [comment]
I thought that too, but discovered on Next there's a stream page called Editorial http://next.ft.com/stream/brandId/NTc3OGYxNTMtZGMzOS00ZDgwLWFiZjYtZjZhNDNlMzQ5MmUy-QnJhbmRz perhaps we could link to that?
