### ISSUE TITLE
Image margin @520 layout

### ISSUE THREAD

**Issue by clmntnbrn** [Financial-Times/next-front-page#31]
Is there any way to ensure the image bottoms line up with the card footers @520 layout? Perhaps by degreasing the padding-top of the text? It's fine if there's >3 lines of text because it looks deliberate, but as per this screenshot it looks like it should line up but doesn't...

![screen shot 2015-06-30 at 11 05 33](https://cloud.githubusercontent.com/assets/12392657/8428645/14e82b28-1f18-11e5-8c5d-e8388f180d8f.png)

**Comment by imranolas** [comment]
Not much can be done in this case. The images will always maintain their aspect ratio and grid span which will result vertical space in some cases.
