### ISSUE TITLE
Markets data items not displaying within the Markets data header on blackberry browser

### ISSUE THREAD

**Issue by dilipvaghela** [Financial-Times/next-front-page#325]
1. Go to next.ft.cm
Result : Markets data items not displaying within the Markets data header.
Expected result : Should display at the top.

Not working on :

Blackberry browser for mobile
Blackberry Z10 - 10.1

![img_20151023_102919](https://cloud.githubusercontent.com/assets/14923859/10691049/058aa4e2-797e-11e5-8eb8-b54408e33184.png)

**Comment by charypar** [comment]
@ironsidevsquincy Am I right in thinking it's because BB is core and doesn't have JS, therefore it won't get markets data?

**Comment by ironsidevsquincy** [comment]
BB isn't even core, which *seems* like a pretty big omission

**Comment by dilipvaghela** [comment]
Uploaded pic for blackberry as well.

**Comment by dilipvaghela** [comment]
Shipped to Jira : https://jira.ft.com/browse/NFT-222
