### ISSUE TITLE
Markets data items not displaying within the Markets data header on windows 8 phone

### ISSUE THREAD

**Issue by dilipvaghela** [Financial-Times/next-front-page#326]
1. Go to next.ft.cm
Result : Markets data items not displaying within the Markets data header.
Expected result : Should display at the top.

Not working on :

Internet explorer for mobile
HTC windows phone  - win 8 

![20151023_111157](https://cloud.githubusercontent.com/assets/14923859/10690078/5cddd158-7977-11e5-90f2-97381039c832.jpg)

**Comment by charypar** [comment]
@dilipvaghela can we have screenshots for these visual issues please?

**Comment by dilipvaghela** [comment]
Sorry for the bad pic.

**Comment by charypar** [comment]
Ha! Good effort :D

**Comment by dilipvaghela** [comment]
Shipped to Jira https://jira.ft.com/browse/NFT-247
