### ISSUE TITLE
Markets data header breaks mobile navigation

### ISSUE THREAD

**Issue by charypar** [Financial-Times/next-front-page#327]
Because the navigation is `position: absolute` (to prevent scrolling) but we need it to get pushed down by market data. 

The result is the user cannot close the navigation.

**Comment by tgabe** [comment]
Looks good.  Tested against:
Chrome mobile (OnePlus One/Cyanogenmod, Nexus 6/Android 5.1.1)
Android stock browser 1.0.2125 (Cyanogenmod, 
Safari mobile ios9 (iPhone 5)
Safari mobile ios 7.1.2 (iPhone 4)
Nexus 5 (FF, Chrome)
FF 41.0.2 (Mac desktop)
Chrome 46 (Mac desktop)
BB Z10
