### ISSUE TITLE
Empty space after page within default & S breakpoint on Firefox

### ISSUE THREAD

**Issue by andygout** [Financial-Times/next-front-page#334]
Firefox: default & S layout in live and prototype

Safari: S layout in live and prototype (appears if attempting to scroll further down the page than bottom (and adjusting window width))

![firefox-s-break-point](https://cloud.githubusercontent.com/assets/10484515/10821033/270c7374-7e48-11e5-9936-c5d7e0ac6553.png)

**Comment by ironsidevsquincy** [comment]
Looks like this is to do with the `sticky` on the header

**Comment by andygout** [comment]
Also happening in Chrome when on fastFT.

**Comment by ironsidevsquincy** [comment]
https://github.com/Financial-Times/n-header-footer/pull/143 should fix
