### ISSUE TITLE
Lead card change @980 layout

### ISSUE THREAD

**Issue by clmntnbrn** [Financial-Times/next-front-page#36]
Could we change the layout of the lead card @980 from this:

![screen shot 2015-06-30 at 11 50 41](https://cloud.githubusercontent.com/assets/12392657/8429307/430bc4be-1f1e-11e5-916e-1f3d8e88bd44.png)

to this (the 520 layout):

![screen shot 2015-06-30 at 11 49 20](https://cloud.githubusercontent.com/assets/12392657/8429283/1f893c6a-1f1e-11e5-8991-e136cf790d27.png)

**Comment by charypar** [comment]
Done in #69
