### ISSUE TITLE
Prototype in IE10/11: Various display problems

### ISSUE THREAD

**Issue by andygout** [Financial-Times/next-front-page#362]
- [x] fastFT logo stretched vertically (1)
- [x] IE10 & 11: Images do not adhere to size of containing element and spill out of card / being hidden behind cards (2)
- [x] Content spills out of card (3)
- [x] Card title merges into standfirst (4)
- [x] IE11: Video cards don't include video & not clickable
- [x] IE8: All content in single column on left
- [x] IE9: Only first column displays
- [x] IE10: Video does not play - displays 'Error' text
- [ ] IE10/11: Opinion - container too high - excessive amount of empty space on cards/space not distributed evenly amongst cards (far right column) (5)
- [ ] IE8: Opinion - inverted commas icon displays as black rectangle (6) (https://financialtimes.slack.com/archives/ft-origami/p1448558341000381)

(1)
![screen shot 2015-11-16 at 11 34 21](https://cloud.githubusercontent.com/assets/10484515/11181018/f7780976-8c56-11e5-889e-a9fa884e2beb.png)

(2)
![screen shot 2015-11-16 at 11 34 35](https://cloud.githubusercontent.com/assets/10484515/11181026/0271d352-8c57-11e5-8d78-ea9a1411f66c.png)

(3)
![screen shot 2015-11-16 at 11 35 13](https://cloud.githubusercontent.com/assets/10484515/11181030/08035aca-8c57-11e5-800e-4af047a7c987.png)

(4)
![screen shot 2015-11-16 at 11 35 05](https://cloud.githubusercontent.com/assets/10484515/11181032/0b0cc58a-8c57-11e5-995b-f8196ff091dd.png)

(5)
![screen shot 2015-11-26 at 16 54 52](https://cloud.githubusercontent.com/assets/10484515/11427912/87899796-945e-11e5-8c98-882b2b7d030f.png)

(6)
![screen shot 2015-11-26 at 17 01 43](https://cloud.githubusercontent.com/assets/10484515/11428252/6ce449ec-9461-11e5-816b-6f934bdcf6ee.png)

**Comment by adgad** [comment]
Seems old. Closing, can keep bugs in Jira.
