### ISSUE TITLE
"Go to" link icons wrong colour

### ISSUE THREAD

**Issue by clmntnbrn** [Financial-Times/next-front-page#42]
Should be #27757B please

**Comment by kaelig** [comment]
FYI, we try to refer to colours as their names in the palette and avoid mentioning hex codes at all (ubiquitous language and all). Happy to help if we need to provide better guidance on that point.

**Comment by clmntnbrn** [comment]
@kaelig where can I find the palette so I can see what the colours have been labeled?

**Comment by charypar** [comment]
@clmntnbrn https://github.com/Financial-Times/o-colors/blob/next/src/scss/_palette.scss

**Comment by kaelig** [comment]
Thanks @charypar. That would be the dev-friendly palette.

@clmntnbrn you'll also find a more readable palette on the color component documentation: http://registry.origami.ft.com/components/o-colors@3.1.0-beta.1 - Hope that helps!

**Comment by charypar** [comment]
@kaelig ooooooh, pretty!

**Comment by kaelig** [comment]
@clmntnbrn @charypar I forgot to mention the Next styleguide itself: http://next.ft.com/__styleguide/design-primitives#palette - much better reference for your use case!
