### ISSUE TITLE
Blackberry 10 Bugs

### ISSUE THREAD

**Issue by aRhombus** [Financial-Times/next-front-page#430]
- [x] Not playing video

- [x] Search not working

- [x] Menu not showing/not linking to navigation items

- [ ]  Toggle showing on top stories and FastFT once FastFT has been clicked. 

- [ ] Markets Data not displaying (only markets data link is visible)

**Comment by dilipvaghela** [comment]
Will review this and report on Jira, I think most of these issues have already been reported on Jira.

**Comment by dilipvaghela** [comment]
- Toggle showing on top stories and FastFT once FastFT has been clicked.
https://jira.ft.com/browse/NFT-144
 - Markets Data not displaying (only markets data link is visible)
https://jira.ft.com/browse/NFT-222

The following issues mentioned above have been shipped to Jira, and the rest of them have been resolved.
