### ISSUE TITLE
Samsung: Chrome/Android browser do not display videos

### ISSUE THREAD

**Issue by andygout** [Financial-Times/next-front-page#459]

**Comment by ironsidevsquincy** [comment]
Browser/OS version?

**Comment by andygout** [comment]
Device has been taken away for weekend - will add on its return.

Possibly requires file to be encoded in way recognised by particular phone model: http://www.recovery-android.com/play-mp4-on-android.html

**Comment by andygout** [comment]
Originally noticed on Samsung S4 Android 5.0.1. and is now working fine.

Have also checked Samsung S6 5.1.1 and also good.

Control and variant checked on both devices.
