### ISSUE TITLE
a11y improvements

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next-front-page#541]
## Landmarks
- [x] No `main` region
- [ ]  Multiple `complementary` regions without associated headings. Should be sections with `aria-labelledby` attribute.
## Content
- [x]  No level 1 heading
- [x]  Cards use level 2 headings (the same as their parent section) so it's not possible to navigate via hierarchy (There are _88_ level 2 headings so it's pretty crazy!).
- [ ] Images with no alt text should have blank alt text attribute to prevent screen readers trying to interpret file name
- [ ] Section headers are within aside elements. This means the heading is for the aside, not for the section. Additionally the section then has an aside with no content in it.
- [ ] FTSE items are headings and shouldn't be
## Widgets
- [ ] Hide the markets data banner or add some context. Links don't mean anything on their own. No indication of up/down state.
- [ ] Edition switcher requires descriptive label. When opening the list focus should be shifted to the first item. Currently no indication of selected edition. Button requires `aria-controls` attribute and `aria-expanded` attribute to convey state. Marking up as a list adds lots of extra noise, consider simply using links.
## Other
- [ ] ~~"Most read by professionals" label is not associated with the dropdown~~
- [ ] Greater than/chevron symbols used as list item markers are read out.

**Comment by GlynnPhillips** [comment]
#669 & [#24 in n-card](https://github.com/Financial-Times/n-card/pull/24) has addressed a couple of these.

- No level 1 heading
- Cards use level 2 headings

They also fixed the skip to content link not working and adding a level 2 heading for top stories to keep the hierarchy

**Comment by i-like-robots** [comment]
Closing this as so much has changed since the issue was created
