### ISSUE TITLE
Flexbox bug in Safari on iOS 6

### ISSUE THREAD

**Issue by clmntnbrn** [Financial-Times/next-front-page#62]

**Comment by charypar** [comment]
Hmmm... Is it even worth supporting iOS 6 any more...?

**Comment by clmntnbrn** [comment]
Also happening on Chrome

**Comment by dilipvaghela** [comment]
What do you mean by this issue ?

**Comment by clmntnbrn** [comment]
@dilipvaghela This was on the old layout, the boxes had no margin - if you can lend me a device with  ios 6 on I can have a look and check

**Comment by dilipvaghela** [comment]
This is now fixed.
