### ISSUE TITLE
Compatibility with new o-header

### ISSUE THREAD

**Issue by andygout** [Financial-Times/next-front-page#658]
Things to address with next beta release of `o-header` (currently at: v.5.0.0-beta.9):-

- [ ] `z-index` value of `o-header`: set in `n-layout`.
https://github.com/Financial-Times/o-header/issues/150
https://github.com/Financial-Times/o-header/issues/151

- [x] S layout subnav: Edition and World both pre-selected (aria-selected: true); should only be Edition.
https://github.com/Financial-Times/o-header/issues/150

- [x] IE8: add to ie8.scss:
$o-header-is-silent: false;
@ import "o-header/main";
https://github.com/Financial-Times/o-header/issues/155

**Comment by aintgoin2goa** [comment]
@andygout is this still required or has it been superseded by the recent header work?

**Comment by andygout** [comment]
Yup - all related to the old header so can be closed. Thanks for flagging.
