### ISSUE TITLE
Review and fix up accesibility of the entire page

### ISSUE THREAD

**Issue by charypar** [Financial-Times/next-front-page#68]
All the layouts and controls need proper accessible markup. Since everything was a bit of an experiment, we haven't done that, but we need to before we launch the MVP.

**Comment by charypar** [comment]
Or just after ;)

**Comment by a-rhombus** [comment]
- [ ] Add alt tags to images

- [ ] When CSS removed, caret navigation currently only highlights "Save" buttons. Add article titles to keyboard navigation.

**Comment by charypar** [comment]
Fixed what I could in #110
