### ISSUE TITLE
img[srcset][sizes], not picture>source[srcset][media]+img

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next-front-page#735]
As we're only dealing with [selecting images based on resolution](http://usecases.responsiveimages.org/#resolution-based-selection) we should use the `<img>` element with associated `srcset` and `sizes`.

The `<picture>` element is for [art direction](http://usecases.responsiveimages.org/#art-direction) use cases (I.E. different crops) which we don't support right now.

There's a few advantages to switching other too:

- Much less markup
- If a browser doesn't support `srcset` it will fallback to `src` no conditional comment hacks

**Comment by i-like-robots** [comment]
Useful reference: https://ericportis.com/posts/2014/srcset-sizes/

**Comment by ironsidevsquincy** [comment]
Interesting, never realised the difference. Good shout, this can be picked up by the performance team I reckon

**Comment by i-like-robots** [comment]
Yes, just discussed this with @wheresrhys =]

**Comment by wheresrhys** [comment]
Related to this, we load picturefill lazily on all browsers, even those that don't CTM so we can maybe get away with no src attribute, except in ie where responsiveness isn't important and loading the default image ASAP is the priority. So how about something like

```
<img <!conditional comment>src="700px" <!close conditional comment> srcset="blah blah">
```

**Comment by wheresrhys** [comment]
Do conditional comments work inside an unclosed tag?

**Comment by wheresrhys** [comment]
no http://stackoverflow.com/questions/5926580/html-comments-inside-opening-tag-of-the-element

but alternatively

```
<!conditional comment>
<img src="image service blah blah700px">
<!else>
<img srcset="blah blah" sizes="blip bloop">
<!close conditional comment> 
```

**Comment by ironsidevsquincy** [comment]
Possibly. Will have to see if the extra markup/complexity is worth it for single browser

**Comment by wheresrhys** [comment]
The main benefit of this (I neglected to mention above) would be enabling us to avoid double image downloads on mobile browsers which don't support srcset natively. The ie stuff is just a fail safe to avoid stakeholders complaining about FONI (flash of no image) on ie

**Comment by ironsidevsquincy** [comment]
Yep, but it still only benefits IE. I'm totally for getting rid of the `src` completely. Will speed up page load too for those browsers that don't understand the `srcset` natively.

**Comment by aintgoin2goa** [comment]
This issues looks to be complete to me can anyone confirm?

**Comment by ironsidevsquincy** [comment]
Yep, should be using https://github.com/Financial-Times/n-image/blob/master/components/image.js everywhere now
