### ISSUE TITLE
Life & Arts, Markets, Technology to full width cards @980 and @520

### ISSUE THREAD

**Issue by clmntnbrn** [Financial-Times/next-front-page#79]

**Comment by kaelig** [comment]
May I suggest using viewport names (S, M, L…) instead of values (520, 980)? It helps achieving parity between code, design and other discussion spaces.

**Comment by charypar** [comment]
@kaelig I find them all the same sort of confusing and going from a number to a browser width to reproduce, then to code is shorter than translating letter to number back to letter :) Just my opinion...
