### ISSUE TITLE
Can we switch Preact to React for clientside JS?

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/next-front-page#874]
I'm making the interactive Brexit live data component, and I'm encountering horrible bugs coming from `preact.js`. When I edit the `webpack.config.js` to remove the 'aliasing' of react to preact-compat, the bugs all go away.

I realise Preact is nice because it's so tiny, but I don't think it's stable enough for serious use.

**Comment by ironsidevsquincy** [comment]
Can you give an example of the bugs?

**Comment by callumlocke** [comment]
I'm using `dangerouslySetInnerHTML` to insert an inline SVG into a div inside a React component. When I render the component, it works fine. But then when it re-renders after a state change, it (sometimes) errors with this:

```
preact.js:158 Uncaught TypeError: Cannot assign to read only property 'height' of object '#<SVGSVGElement>'
```

I'm not sure if it should even be trying to efficiently DOM-diff inside the `dangerouslySetInnerHTML` subtree at all. Either way, my SVG doesn't even change between renders, it's the same SVG string every time (the re-render should only be changing other things in the component, outside the SVG). This sounds like a bug in Preact and I'm not sure how to work around it. Switching to React fixes it completely.

Also, I've found Preact accepts stuff like `<path stroke-width="...">` while React only allows `<path strokeWidth="...">`, which not itself a big deal but it's evidence that Preact is not really a drop-in replacement for React. So I'm not sure it's a good idea to transparently alias it in the webpack config.

**Comment by wheresrhys** [comment]
What are you building in react that couldn't be built fairly easily without react? Or (given front page expects a degree of react server side) built on react server side and implemented in vanilla js client side. I'm not saying it's necessarily unjustified, but it'd be good to see the use case.

Also, have you tried debugging inside preact to see if you can fix it? One reason @i-like-robots gives for using preact is it is a genuinely open source project - not a semi-closed shop like react - so we can contribute bug fixes, or fork it for a while if need be. 

However, if you really *need* to use masses of javascript that will slow down the whole experience in many devices, aka react, you'll be glad to hear that with the shared js bundle (hopefully rolling out very soon, just got to address some platinumification issues) it should be possible to use react in the page's bundle but preact in the bits shared between pages (hopefully, with some refactoring from the @Financial-Times/next-myft team we can also remove preact from the shared bundle altogether, thereby making n-ui wholly unopinionated about it)

> So I'm not sure it's a good idea to transparently alias it in the webpack config.

I could be sold on this. It was the easiest way at the time to apply preact quickly to avoid react being included on every page via n-ui, even when not needed. If an easy to rollout alternative is found I'd be happy to try it

**Comment by callumlocke** [comment]
I'm rewriting all clientside logic in vanilla JS to avoid preact

**Comment by wheresrhys** [comment]
Thanks (and sorry)

Once the myft-ui has been refactored to be more granular (cc @Financial-Times/next-myft ) I can remove preact from the shared n-ui bundle, and leave opinions about react/react-like things to each app individually. (although I'd personally oppose using react for all but the most complex UIs)
