### ISSUE TITLE
Duplicate stylesheets when developing locally

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/next-front-page#884]
![image](https://cloud.githubusercontent.com/assets/250617/16226944/c92c3e2a-37a5-11e6-88e1-23efc1f9deec.png)

I only wrote the above rule once, but it appears three times in devtools. Makes debugging styles in the browser a nightmare. Is this a webpack config bug?

**Comment by ironsidevsquincy** [comment]
Hmmm, weird. Might be, don't haven't seen this happen before. Where's this sass in the source?

**Comment by callumlocke** [comment]
Oh wow, I just found I was importing a partial in two places. I've been finding this really annoying for days. LOL

So I'm no longer getting triple styles, but still getting double styles... And I can't find any other repeated `@import` anywhere. So I'm wondering if this could actually still be a webpack config issue. I'll keep looking
