### ISSUE TITLE
Edition switcher does the opposite of what most people think

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/next-front-page#961]
I asked ten people in the next team to answer this question:

"Are you on the UK edition or the International edition?" 

![image](https://cloud.githubusercontent.com/assets/224547/17215195/fd9382a4-54d3-11e6-94e2-6964510f94bf.png)

Nine out of ten people said that it's on the International edition, because you can click to the UK Edition.

Guess what? Nine out of ten people get it wrong.

![image](https://cloud.githubusercontent.com/assets/224547/17215150/d159eca0-54d3-11e6-9205-bb84eea163d2.png)

Surprise! You're on the UK Edition!

-----------------------------------

The immediate fix would be to swap the link color and underline effect from whatever version it is now to the other version.

**Comment by ironsidevsquincy** [comment]
Woah. Yeah, that's v weird. This is part of [o-header](https://github.com/Financial-Times/o-header), so best to raise the issue there

**Comment by adambraimbridge** [comment]
Thanks @ironsidevsquincy, I've copied it to https://github.com/Financial-Times/o-header/issues/201.
